FROM drupal:11-php8.3-fpm

RUN pecl install redis && docker-php-ext-enable redis

RUN apt-get update -qq &&     DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends       texlive-xetex       texlive-fonts-recommended       texlive-latex-extra       poppler-utils       ghostscript       default-mysql-client &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*

RUN xelatex --version
